openapi: 3.0.3
info:
  title: VoAI Voices API
  description: API for voice management with enhanced metadata and filtering
  version: 1.0.0

paths:
  /api/v1/voices:
    get:
      summary: List available voices
      description: |
        List all available voices with optional filtering by provider, language, gender, age group, and style.
        Voices marked as deprecated are excluded by default.
      operationId: listVoices
      tags:
        - Voices
      parameters:
        - name: provider
          in: query
          description: Filter by provider (azure, gcp, elevenlabs, openai, cartesia, deepgram)
          schema:
            type: string
            enum: [azure, gcp, elevenlabs, openai, cartesia, deepgram]
        - name: language
          in: query
          description: Filter by language code (e.g., zh-TW, en-US)
          schema:
            type: string
            example: zh-TW
        - name: gender
          in: query
          description: Filter by gender
          schema:
            type: string
            enum: [male, female, neutral]
        - name: age_group
          in: query
          description: Filter by age group
          schema:
            type: string
            enum: [child, young, adult, senior]
        - name: style
          in: query
          description: Filter by style (e.g., news, conversation, cheerful)
          schema:
            type: string
        - name: include_deprecated
          in: query
          description: Include deprecated voices in results
          schema:
            type: boolean
            default: false
        - name: limit
          in: query
          description: Maximum number of results
          schema:
            type: integer
            minimum: 1
            maximum: 500
            default: 100
        - name: offset
          in: query
          description: Number of results to skip
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: List of voices
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoiceListResponse'
        '400':
          description: Invalid filter parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/voices/{voice_id}:
    get:
      summary: Get voice details
      description: Get detailed information about a specific voice including all metadata
      operationId: getVoice
      tags:
        - Voices
      parameters:
        - name: voice_id
          in: path
          required: true
          description: Voice ID in format "provider:voice_id"
          schema:
            type: string
            example: "azure:zh-TW-HsiaoYuNeural"
      responses:
        '200':
          description: Voice details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoiceDetail'
        '404':
          description: Voice not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    VoiceListResponse:
      type: object
      required:
        - voices
        - total
        - limit
        - offset
      properties:
        voices:
          type: array
          items:
            $ref: '#/components/schemas/VoiceSummary'
        total:
          type: integer
          description: Total number of voices matching the filter
          example: 150
        limit:
          type: integer
          example: 100
        offset:
          type: integer
          example: 0
        cached_at:
          type: string
          format: date-time
          description: Timestamp when voice data was last synced
          example: "2026-01-22T10:30:00Z"

    VoiceSummary:
      type: object
      required:
        - id
        - provider
        - voice_id
        - name
        - language
      properties:
        id:
          type: string
          description: Unique voice identifier (provider:voice_id)
          example: "azure:zh-TW-HsiaoYuNeural"
        provider:
          type: string
          enum: [azure, gcp, elevenlabs, openai, cartesia, deepgram]
          example: azure
        voice_id:
          type: string
          description: Provider-specific voice ID
          example: "zh-TW-HsiaoYuNeural"
        name:
          type: string
          description: Display name
          example: "曉雨"
        language:
          type: string
          description: Language code
          example: "zh-TW"
        gender:
          type: string
          enum: [male, female, neutral]
          nullable: true
          example: female
        age_group:
          type: string
          enum: [child, young, adult, senior]
          nullable: true
          example: adult
        styles:
          type: array
          items:
            type: string
          description: Available styles for this voice
          example: ["cheerful", "sad", "angry"]

    VoiceDetail:
      allOf:
        - $ref: '#/components/schemas/VoiceSummary'
        - type: object
          properties:
            use_cases:
              type: array
              items:
                type: string
              description: Recommended use cases
              example: ["narration", "assistant", "audiobook"]
            description:
              type: string
              description: Voice description
              example: "年輕女性，溫暖親切的聲音"
            sample_audio_url:
              type: string
              format: uri
              nullable: true
              description: URL to sample audio
              example: "https://example.com/samples/hsiao-yu.mp3"
            is_deprecated:
              type: boolean
              description: Whether the voice has been deprecated by provider
              default: false
            metadata:
              type: object
              additionalProperties: true
              description: Provider-specific metadata
            synced_at:
              type: string
              format: date-time
              description: Last sync timestamp
              example: "2026-01-22T10:30:00Z"
            updated_at:
              type: string
              format: date-time
              description: Last update timestamp
              example: "2026-01-22T10:30:00Z"

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "VOICE_NOT_FOUND"
        message:
          type: string
          description: Human-readable error message
          example: "Voice with ID 'azure:invalid-voice' not found"
        details:
          type: object
          additionalProperties: true
          description: Additional error details
