"""add_stt_tables

Revision ID: 477f0ffdd804
Revises: 20260118_100000
Create Date: 2026-01-19 10:55:41.239095

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "477f0ffdd804"
down_revision: str | None = "20260118_100000"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("format", sa.String(length=10), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.String(length=512), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_audio_file_created", "audio_files", ["created_at"], unique=False)
    op.create_index("idx_audio_file_user_id", "audio_files", ["user_id"], unique=False)
    op.create_table(
        "ground_truths",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("audio_file_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["audio_file_id"], ["audio_files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("audio_file_id"),
    )
    op.create_table(
        "transcription_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("audio_file_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("child_mode", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["audio_file_id"], ["audio_files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_transcription_request_audio", "transcription_requests", ["audio_file_id"], unique=False
    )
    op.create_index(
        "idx_transcription_request_status", "transcription_requests", ["status"], unique=False
    )
    op.create_table(
        "transcription_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["request_id"], ["transcription_requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_index(
        "idx_transcription_result_request", "transcription_results", ["request_id"], unique=False
    )
    op.create_table(
        "wer_analyses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("result_id", sa.UUID(), nullable=False),
        sa.Column("ground_truth_id", sa.UUID(), nullable=False),
        sa.Column("error_rate", sa.Float(), nullable=False),
        sa.Column("error_type", sa.String(length=10), nullable=False),
        sa.Column("insertions", sa.Integer(), nullable=False),
        sa.Column("deletions", sa.Integer(), nullable=False),
        sa.Column("substitutions", sa.Integer(), nullable=False),
        sa.Column("alignment", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["ground_truth_id"], ["ground_truths.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["result_id"], ["transcription_results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("result_id"),
    )
    op.create_index("idx_wer_analysis_result", "wer_analyses", ["result_id"], unique=False)
    op.create_table(
        "word_timings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("result_id", sa.UUID(), nullable=False),
        sa.Column("word", sa.String(length=255), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["result_id"], ["transcription_results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "synthesis_logs",
        "speed",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("'1'::double precision"),
    )
    op.alter_column(
        "synthesis_logs",
        "output_format",
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
        existing_server_default=sa.text("'''mp3'''::character varying"),
    )
    op.alter_column(
        "synthesis_logs",
        "output_mode",
        existing_type=sa.VARCHAR(length=16),
        nullable=False,
        existing_server_default=sa.text("'''batch'''::character varying"),
    )
    op.drop_index(op.f("idx_users_email"), table_name="users")
    op.drop_index(op.f("idx_users_google_id"), table_name="users")
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.drop_constraint(op.f("users_google_id_key"), "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=True)
    op.alter_column(
        "voice_cache",
        "styles",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'[]'::json"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "voice_cache",
        "styles",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'[]'::json"),
    )
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("users_google_id_key"), "users", ["google_id"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("idx_users_google_id"), "users", ["google_id"], unique=False)
    op.create_index(op.f("idx_users_email"), "users", ["email"], unique=False)
    op.alter_column(
        "synthesis_logs",
        "output_mode",
        existing_type=sa.VARCHAR(length=16),
        nullable=True,
        existing_server_default=sa.text("'''batch'''::character varying"),
    )
    op.alter_column(
        "synthesis_logs",
        "output_format",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
        existing_server_default=sa.text("'''mp3'''::character varying"),
    )
    op.alter_column(
        "synthesis_logs",
        "speed",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("'1'::double precision"),
    )
    op.drop_table("word_timings")
    op.drop_index("idx_wer_analysis_result", table_name="wer_analyses")
    op.drop_table("wer_analyses")
    op.drop_index("idx_transcription_result_request", table_name="transcription_results")
    op.drop_table("transcription_results")
    op.drop_index("idx_transcription_request_status", table_name="transcription_requests")
    op.drop_index("idx_transcription_request_audio", table_name="transcription_requests")
    op.drop_table("transcription_requests")
    op.drop_table("ground_truths")
    op.drop_index("idx_audio_file_user_id", table_name="audio_files")
    op.drop_index("idx_audio_file_created", table_name="audio_files")
    op.drop_table("audio_files")
    # ### end Alembic commands ###
