openapi: 3.1.0
info:
  title: Provider Credentials API
  description: API for managing TTS/STT provider API keys (BYOL - Bring Your Own License)
  version: 1.0.0
  contact:
    name: Voice Lab Team

servers:
  - url: /api/v1
    description: API v1

tags:
  - name: Credentials
    description: API key management operations
  - name: Providers
    description: Provider information and models

paths:
  /credentials:
    get:
      summary: List user's provider credentials
      description: Returns all configured provider credentials for the authenticated user (masked keys)
      operationId: listCredentials
      tags: [Credentials]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  credentials:
                    type: array
                    items:
                      $ref: '#/components/schemas/CredentialSummary'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      summary: Add a new provider credential
      description: |
        Add an API key for a TTS/STT provider. The key is validated against
        the provider's API before being stored (encrypted).
      operationId: addCredential
      tags: [Credentials]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCredentialRequest'
      responses:
        '201':
          description: Credential created and validated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialResponse'
        '400':
          description: Invalid request or validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          description: Credential already exists for this provider
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /credentials/{credentialId}:
    parameters:
      - name: credentialId
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: Get credential details
      description: Returns details of a specific credential (masked key)
      operationId: getCredential
      tags: [Credentials]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Credential details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update credential
      description: Update API key and/or selected model for a provider
      operationId: updateCredential
      tags: [Credentials]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCredentialRequest'
      responses:
        '200':
          description: Credential updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialResponse'
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete credential
      description: Remove an API key from the system
      operationId: deleteCredential
      tags: [Credentials]
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Credential deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /credentials/{credentialId}/validate:
    parameters:
      - name: credentialId
        in: path
        required: true
        schema:
          type: string
          format: uuid

    post:
      summary: Re-validate credential
      description: Re-check if the stored API key is still valid
      operationId: validateCredential
      tags: [Credentials]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResult'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /credentials/{credentialId}/models:
    parameters:
      - name: credentialId
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: List available models
      description: Get available models for a provider using the stored credential
      operationId: listModels
      tags: [Credentials]
      security:
        - bearerAuth: []
      parameters:
        - name: language
          in: query
          required: false
          schema:
            type: string
          description: Filter by language code (e.g., zh-TW)
      responses:
        '200':
          description: List of models
          content:
            application/json:
              schema:
                type: object
                properties:
                  models:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProviderModel'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /providers:
    get:
      summary: List supported providers
      description: Get all supported TTS/STT providers
      operationId: listProviders
      tags: [Providers]
      responses:
        '200':
          description: List of providers
          content:
            application/json:
              schema:
                type: object
                properties:
                  providers:
                    type: array
                    items:
                      $ref: '#/components/schemas/Provider'

  /providers/{providerId}:
    parameters:
      - name: providerId
        in: path
        required: true
        schema:
          type: string
          enum: [elevenlabs, azure, gemini]

    get:
      summary: Get provider details
      description: Get details about a specific provider
      operationId: getProvider
      tags: [Providers]
      responses:
        '200':
          description: Provider details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Provider'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AddCredentialRequest:
      type: object
      required:
        - provider
        - api_key
      properties:
        provider:
          type: string
          enum: [elevenlabs, azure, gemini]
          description: Provider identifier
        api_key:
          type: string
          minLength: 1
          maxLength: 256
          description: Provider API key
        selected_model_id:
          type: string
          description: Optional model to select

    UpdateCredentialRequest:
      type: object
      properties:
        api_key:
          type: string
          minLength: 1
          maxLength: 256
          description: New API key (optional, triggers revalidation)
        selected_model_id:
          type: string
          description: Model to select

    CredentialSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        provider:
          type: string
        provider_display_name:
          type: string
        masked_key:
          type: string
          example: "****abc1"
        is_valid:
          type: boolean
        selected_model_id:
          type: string
          nullable: true
        last_validated_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time

    CredentialResponse:
      allOf:
        - $ref: '#/components/schemas/CredentialSummary'
        - type: object
          properties:
            updated_at:
              type: string
              format: date-time

    ValidationResult:
      type: object
      properties:
        is_valid:
          type: boolean
        validated_at:
          type: string
          format: date-time
        error_message:
          type: string
          nullable: true

    ValidationError:
      type: object
      properties:
        error:
          type: string
          example: "validation_failed"
        message:
          type: string
          example: "API key validation failed"
        details:
          type: object
          properties:
            provider_error:
              type: string
              description: Error message from provider

    Provider:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        display_name:
          type: string
        type:
          type: array
          items:
            type: string
            enum: [tts, stt]
        is_active:
          type: boolean

    ProviderModel:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        language:
          type: string
        gender:
          type: string
          nullable: true
        description:
          type: string
          nullable: true

    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string

  responses:
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "unauthorized"
            message: "Authentication required"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "not_found"
            message: "Resource not found"
