openapi: 3.0.3
info:
  title: Voice Lab Music Generation API
  description: |
    音樂生成 API，整合 Mureka AI 平台提供歌曲、純音樂（BGM）和歌詞生成功能。
  version: 1.0.0
  contact:
    name: Voice Lab Team

servers:
  - url: /api/v1
    description: API v1

tags:
  - name: music
    description: 音樂生成相關操作
  - name: quota
    description: 配額管理

paths:
  /music/instrumental:
    post:
      tags:
        - music
      summary: 提交純音樂生成任務
      description: 根據情境描述生成純音樂/背景音樂（BGM）
      operationId: submitInstrumental
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstrumentalRequest'
      responses:
        '201':
          description: 任務已建立
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MusicGenerationJob'
        '400':
          description: 請求參數錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: 配額不足或並發上限
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /music/song:
    post:
      tags:
        - music
      summary: 提交歌曲生成任務
      description: 根據歌詞和風格描述生成完整歌曲（含人聲）
      operationId: submitSong
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SongRequest'
      responses:
        '201':
          description: 任務已建立
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MusicGenerationJob'
        '400':
          description: 請求參數錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: 配額不足或並發上限
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /music/lyrics:
    post:
      tags:
        - music
      summary: 提交歌詞生成任務
      description: 根據主題描述生成結構化歌詞
      operationId: submitLyrics
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LyricsRequest'
      responses:
        '201':
          description: 任務已建立
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MusicGenerationJob'
        '400':
          description: 請求參數錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: 配額不足或並發上限
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /music/lyrics/extend:
    post:
      tags:
        - music
      summary: 延伸歌詞
      description: 延伸現有歌詞，增加新的段落
      operationId: extendLyrics
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExtendLyricsRequest'
      responses:
        '201':
          description: 任務已建立
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MusicGenerationJob'
        '400':
          description: 請求參數錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /music/jobs:
    get:
      tags:
        - music
      summary: 列出音樂生成任務
      description: 取得當前用戶的音樂生成任務列表
      operationId: listJobs
      parameters:
        - name: status
          in: query
          description: 篩選特定狀態的任務
          schema:
            $ref: '#/components/schemas/MusicGenerationStatus'
        - name: type
          in: query
          description: 篩選特定類型的任務
          schema:
            $ref: '#/components/schemas/MusicGenerationType'
        - name: limit
          in: query
          description: 每頁數量
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
        - name: offset
          in: query
          description: 分頁偏移
          schema:
            type: integer
            default: 0
            minimum: 0
      responses:
        '200':
          description: 任務列表
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobListResponse'

  /music/jobs/{job_id}:
    get:
      tags:
        - music
      summary: 查詢單一任務狀態
      description: 取得特定音樂生成任務的詳細資訊
      operationId: getJob
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 任務詳情
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MusicGenerationJob'
        '404':
          description: 任務不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /music/jobs/{job_id}/download:
    get:
      tags:
        - music
      summary: 下載生成結果
      description: 下載已完成任務的音檔
      operationId: downloadJob
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 音檔內容
          content:
            audio/mpeg:
              schema:
                type: string
                format: binary
        '400':
          description: 任務未完成
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: 任務不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /music/jobs/{job_id}/retry:
    post:
      tags:
        - music
      summary: 重新提交失敗任務
      description: 以相同參數重新提交失敗的任務
      operationId: retryJob
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '201':
          description: 新任務已建立
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MusicGenerationJob'
        '400':
          description: 任務狀態不允許重試
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: 任務不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /music/quota:
    get:
      tags:
        - quota
      summary: 查詢配額使用狀況
      description: 取得當前用戶的配額使用統計
      operationId: getQuota
      responses:
        '200':
          description: 配額狀態
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuotaStatus'

components:
  schemas:
    MusicGenerationType:
      type: string
      enum:
        - song
        - instrumental
        - lyrics
      description: |
        音樂生成類型
        - song: 歌曲（含人聲）
        - instrumental: 純音樂/BGM
        - lyrics: 歌詞

    MusicGenerationStatus:
      type: string
      enum:
        - pending
        - processing
        - completed
        - failed
      description: |
        任務狀態
        - pending: 等待處理
        - processing: 生成中
        - completed: 已完成
        - failed: 失敗

    MusicModel:
      type: string
      enum:
        - auto
        - mureka-01
        - v7.5
        - v6
      default: auto
      description: |
        Mureka 模型選擇
        - auto: 自動選擇最適合模型
        - mureka-01: 最新旗艦模型
        - v7.5: 平衡型模型
        - v6: 經典穩定模型

    InstrumentalRequest:
      type: object
      required:
        - prompt
      properties:
        prompt:
          type: string
          description: 情境/風格描述
          example: "magical fantasy forest, whimsical, children friendly"
          minLength: 10
          maxLength: 500
        model:
          $ref: '#/components/schemas/MusicModel'

    SongRequest:
      type: object
      properties:
        prompt:
          type: string
          description: 風格描述
          example: "pop, cheerful, children, chinese, female vocal"
          maxLength: 500
        lyrics:
          type: string
          description: 歌詞內容
          maxLength: 3000
        model:
          $ref: '#/components/schemas/MusicModel'

    LyricsRequest:
      type: object
      required:
        - prompt
      properties:
        prompt:
          type: string
          description: 主題描述
          example: "太空探險"
          minLength: 2
          maxLength: 200

    ExtendLyricsRequest:
      type: object
      required:
        - lyrics
      properties:
        lyrics:
          type: string
          description: 現有歌詞
          maxLength: 3000
        prompt:
          type: string
          description: 延伸方向描述
          maxLength: 200

    MusicGenerationJob:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 任務 ID
        type:
          $ref: '#/components/schemas/MusicGenerationType'
        status:
          $ref: '#/components/schemas/MusicGenerationStatus'
        prompt:
          type: string
          description: 輸入的描述
        lyrics:
          type: string
          description: 輸入的歌詞
        model:
          $ref: '#/components/schemas/MusicModel'
        result_url:
          type: string
          format: uri
          description: 音檔下載 URL（完成後提供）
        cover_url:
          type: string
          format: uri
          description: 封面圖片 URL
        generated_lyrics:
          type: string
          description: AI 生成的歌詞
        duration_ms:
          type: integer
          description: 音樂時長（毫秒）
        title:
          type: string
          description: 生成的標題
        created_at:
          type: string
          format: date-time
          description: 建立時間
        started_at:
          type: string
          format: date-time
          description: 開始處理時間
        completed_at:
          type: string
          format: date-time
          description: 完成時間
        error_message:
          type: string
          description: 錯誤訊息（失敗時提供）

    JobListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/MusicGenerationJob'
        total:
          type: integer
          description: 總數量
        limit:
          type: integer
          description: 每頁數量
        offset:
          type: integer
          description: 分頁偏移

    QuotaStatus:
      type: object
      properties:
        daily_used:
          type: integer
          description: 今日已使用
        daily_limit:
          type: integer
          description: 每日限制
        monthly_used:
          type: integer
          description: 本月已使用
        monthly_limit:
          type: integer
          description: 每月限制
        concurrent_jobs:
          type: integer
          description: 目前進行中的任務數
        max_concurrent_jobs:
          type: integer
          description: 最大並發任務數
        can_submit:
          type: boolean
          description: 是否可提交新任務

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: 錯誤代碼
          example: "QUOTA_EXCEEDED"
        message:
          type: string
          description: 錯誤訊息
          example: "音樂生成配額不足，請聯繫管理員"
        details:
          type: object
          description: 額外錯誤詳情
